# srcs/docker-compose.yml

services:
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb:/var/lib/mysql
    # environment:
      # - MYSQL_DATABASE=wordpress
      # - MYSQL_USER=msquser
      # - MYSQL_PASSWORD=123456
      # - MYSQL_ROOT_PASSWORD=0123456
    env_file:
      - .env
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    # environment:
      # - WORDPRESS_DB_HOST=mariadb
      # - WORDPRESS_DB_NAME=wordpress
      # - WORDPRESS_DB_USER=msquser
      # - WORDPRESS_DB_PASSWORD=123456
    env_file:
      - .env
    networks:
      - inception_network


# volumes:
#   wordpress_data:
#     driver: local
#   mariadb_data:
#     driver: local

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aouhbi/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/aouhbi/data/mariadb

networks:
  inception_network:
    driver: bridge